import type { InvoiceDocument } from '../../models/billing/Invoice';
import type { CustomerDocument } from '../../models/billing/Customer';
import type { LedgerTransactionDocument } from '../../models/billing/LedgerTransaction';
import { fromMinor, roundMoney } from '../../utils/money';

interface Line {
  description: string;
  quantity: number;
  unitPriceMinor: number;
  amountMinor: number;
}

/**
 * Generate a print-ready professional invoice PDF.
 *
 * This is a self-contained, dependency-free PDF builder (subset of the PDF 1.4
 * spec using standard fonts) so no native rendering / headless-browser
 * dependency is required. It is suitable for Download and Print-from-browser.
 */
export function buildInvoicePdf(params: {
  company: { name: string; line1?: string; line2?: string; email?: string };
  customer: CustomerDocument;
  invoice: InvoiceDocument;
  payments: LedgerTransactionDocument[];
  lines: Line[];
}): { buffer: Buffer; contentType: string; filename: string } {
  const { company, customer, invoice, payments, lines } = params;
  const currency = invoice.currency;
  const fmt = (minor: number) => `${currency} ${roundMoney(fromMinor(minor)).toFixed(2)}`;

  // ---- Content assembly (raw PDF text operators) ----
  const out: string[] = [];
  let y = 800;

  out.push('BT');
  out.push('/F1 20 Tf');
  out.push('50 ' + y + ' Td');
  out.push(`(${escapePdf(company.name)}) Tj`);
  out.push('ET');
  y -= 22;

  out.push('BT');
  out.push('/F1 10 Tf');
  out.push('50 ' + y + ' Td');
  const companyLines = [company.line1, company.line2, company.email].filter(Boolean).join(' | ');
  out.push(`(${escapePdf(companyLines)}) Tj`);
  out.push('ET');
  y -= 40;

  // Invoice + customer header block
  const header: string[] = [];
  header.push(`INVOICE ${invoice.invoiceNumber}`);
  header.push(`Invoice date: ${invoice.issueDate.toISOString().slice(0, 10)}`);
  header.push(`Due date: ${invoice.dueDate.toISOString().slice(0, 10)}`);
  header.push(`Status: ${invoice.status}`);
  header.push(`Bill to: ${customer.name}`);
  y = 760;
  for (const h of header) {
    out.push('BT');
    out.push('/F1 11 Tf');
    out.push('50 ' + y + ' Td');
    out.push(`(${escapePdf(h)}) Tj`);
    out.push('ET');
    y -= 18;
  }
  y -= 20;

  // Table header
  out.push('BT');
  out.push('/F1 10 Tf');
  out.push('50 ' + y + ' Td');
  out.push('(Description                         Qty      Unit        Amount) Tj');
  out.push('ET');
  y -= 14;

  for (const line of lines) {
    const row = `${line.description.slice(0, 34).padEnd(36)} ${String(line.quantity).slice(0, 6).padEnd(7)} ${fmt(line.unitPriceMinor).slice(0, 9).padEnd(11)} ${fmt(line.amountMinor)}`;
    out.push('BT');
    out.push('/F1 10 Tf');
    out.push('50 ' + y + ' Td');
    out.push(`(${escapePdf(row)}) Tj`);
    out.push('ET');
    y -= 14;
  }
  y -= 16;

  const totals: string[] = [
    `Subtotal         ${fmt(invoice.subtotalMinor)}`,
    `Tax              ${fmt(invoice.taxMinor)}`,
    `Discount         ${fmt(invoice.discountMinor)}`,
    `TOTAL DUE        ${fmt(invoice.totalMinor)}`,
  ];
  for (const t of totals) {
    out.push('BT');
    out.push('/F1 10 Tf');
    out.push('50 ' + y + ' Td');
    out.push(`(${escapePdf(t)}) Tj`);
    out.push('ET');
    y -= 14;
  }
  y -= 20;

  out.push('BT');
  out.push('/F1 10 Tf');
  out.push('50 ' + y + ' Td');
  out.push(`(Payments: ${payments.length}) Tj`);
  out.push('ET');
  y -= 14;
  for (const p of payments.slice(0, 5)) {
    out.push('BT');
    out.push('/F1 9 Tf');
    out.push('50 ' + y + ' Td');
    out.push(`(${escapePdf(`${p.transactionId}  ${p.status}  ${fmt(p.amountMinor)}`)}) Tj`);
    out.push('ET');
    y -= 12;
  }

  const content = out.join('\n');

  // ---- PDF object assembly ----
  const objects: string[] = [];
  objects.push('<< /Type /Catalog /Pages 2 0 R >>'); // 1
  objects.push('<< /Type /Pages /Kids [3 0 R] /Count 1 >>'); // 2
  objects.push('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>'); // 3
  objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'); // 4
  const stream = `BT\n/F1 10 Tf\n50 50 Td\n(${escapePdf(`Generated by LedgerGuard on ${new Date().toISOString()}`)}) Tj\nET\n${content}`;
  objects.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`); // 5

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];
  objects.forEach((obj, i) => {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${obj}\nendobj\n`;
  });
  const xrefPos = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const off of offsets) {
    pdf += `${String(off).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefPos}\n%%EOF`;

  const filename = `invoice-${invoice.invoiceNumber}.pdf`;
  return {
    buffer: Buffer.from(pdf, 'latin1'),
    contentType: 'application/pdf',
    filename,
  };
}

function escapePdf(value: string): string {
  return value.replace(/([\\()])/g, '\\$1');
}